Repository foundation-model-stack/fms-model-optimizer, pull requests merged in 2025-07, with the labels that each got.

#152 fix: Saved qconfig recipe being overwritten with defaults
  fms_mo/utils/qconfig_utils.py
  tests/models/test_saveconfig.py
Labels: fix

#156 fix: Remove gptqmodel Warning on startup
  fms_mo/custom_ext_kernels/utils.py
  fms_mo/modules/linear.py
  fms_mo/utils/custom_gptq_models.py
Labels: fix

#157 fix: Remove llmcompressor oneshot import deprecation warning
  examples/FP8_QUANT/README.md
  fms_mo/run_quant.py
Labels: fix

#159 feat: AIU sim for FP8 (DL8/DL16) added to triton kernel
  fms_mo/custom_ext_kernels/triton_kernels.py
  fms_mo/custom_ext_kernels/utils.py
  fms_mo/dq.py
  fms_mo/fx/dynamo_utils.py
  fms_mo/fx/utils.py
  fms_mo/modules/linear.py
  fms_mo/quant/ptq.py
  fms_mo/training_args.py
  fms_mo/utils/dq_utils.py
Labels: feat

#162 feat: Per-sequence scaling in FP8 attention, FP8 fixes
  fms_mo/aiu_addons/fp8/fp8_attn.py
  fms_mo/aiu_addons/fp8/fp8_linear.py
  fms_mo/aiu_addons/fp8/fp8_spyre_op.py
Labels: bug, enhancement, feat

#163 fix: Mark FP8 scale to have the same batch size as input
  fms_mo/aiu_addons/fp8/fp8_attn.py
Labels: fix

#168 fix: Add version limits for torchao, ensure compat with 0.12 + AIU
  fms_mo/aiu_addons/fp8/fp8_linear.py
  pyproject.toml
  tox.ini
Labels: fix
