Repository foundation-model-stack/fms-model-optimizer, pull requests merged in 2025-02, with the labels that each got.

#53 feat: added granite support; fixed adapters to ignore model_config
  fms_mo/aiu_addons/__init__.py
  fms_mo/aiu_addons/gptq/gptq_aiu_adapter.py
  fms_mo/aiu_addons/gptq/gptq_aiu_linear.py
  fms_mo/aiu_addons/gptq/gptq_aiu_op.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_linear.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_op.py
  pyproject.toml
Labels: enhancement, feat

#61 fix: Triton kernel bug fix
  examples/QAT_INT8/run_qa_no_trainer_qat.py
  fms_mo/custom_ext_kernels/triton_kernels.py
  fms_mo/modules/linear.py
  pyproject.toml
Labels: bug, dependencies, fix

#65 feat: Support for int8 smoothquant
  fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_linear.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_op.py
Labels: feat

#62 test: Unit test int8
  fms_mo/aiu_addons/gptq/gptq_aiu_linear.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_op.py
  pyproject.toml
  tests/aiu_addons/conftest.py
  tests/aiu_addons/test_int8_addon.py
  tests/artifacts/aiu_addons/ref_w-per_tensor_a-per_tensor_symm_sq-N.pt
Labels: test

#69 fix: bug fix and minor changes on triton kernel:
  fms_mo/custom_ext_kernels/triton_kernels.py
  fms_mo/run_quant.py
  fms_mo/training_args.py
Labels: fix

#68 fix: handle linear_type callable at int8 linear instantiation
  fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_linear.py
Labels: fix

#70 fix: multiple bug fixes:
  .gitignore
  .spellcheck-en-custom.txt
  examples/FP8_QUANT/README.md
  fms_mo/dq.py
  fms_mo/modules/linear.py
  fms_mo/quant/ptq.py
  fms_mo/training_args.py
  fms_mo/utils/dq_utils.py
Labels: fix

#72 feat: improve transformers tracing for last layers
  fms_mo/dq.py
  fms_mo/fx/dynamo_utils.py
  fms_mo/training_args.py
Labels: feat

#74 fix: in DQ example, when nbits_kvcache=8, context manager will detect incorrect frame
  fms_mo/dq.py
  fms_mo/utils/utils.py
Labels: fix
