Repository foundation-model-stack/fms-model-optimizer, pull requests merged in 2025-06, with the labels that each got.

#102 feat: GPTQModel Migration
  .pylintrc
  .spellcheck-en-custom.txt
  README.md
  docs/fms_mo_design.md
  examples/GPTQ/README.md
  fms_mo/custom_ext_kernels/utils.py
  fms_mo/fx/utils.py
  fms_mo/modules/linear.py
  fms_mo/run_quant.py
  fms_mo/training_args.py
  fms_mo/utils/custom_gptq_models.py
  fms_mo/utils/import_utils.py
  pyproject.toml
  tests/build/test_launch_script.py
Labels: feat

#126 test: Add tests for save_for_aiu functionality w/ tiny models
  .gitignore
  fms_mo/quant/quantizers.py
  fms_mo/utils/aiu_utils.py
  fms_mo/utils/qconfig_utils.py
  tests/models/conftest.py
  tests/models/test_model_utils.py
  tests/models/test_mx.py
  tests/models/test_qmodelprep.py
  tests/models/test_save_aiu.py
  tests/models/test_saveconfig.py
  tests/models/test_toymodels.py
Labels: test

#132 fix: Update GPTQ example README.md for typo
  examples/GPTQ/README.md
Labels: fix

#135 docs: Fix README typo
  examples/GPTQ/README.md
Labels: docs

#131 feat: add guards to sawb recomputation
  fms_mo/utils/aiu_utils.py
Labels: feat

#146 build: Move triton to an optional dependency
  README.md
  fms_mo/custom_ext_kernels/triton_kernels.py
  pyproject.toml
  tests/triton_kernels/test_triton_mm.py
Labels: build

#147 build: Make non-essential dependencies optional
  README.md
  fms_mo/aiu_addons/gptq/gptq_aiu_adapter.py
  fms_mo/aiu_addons/gptq/gptq_aiu_linear.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py
  fms_mo/aiu_addons/i8i8/i8i8_aiu_linear.py
  fms_mo/quant/ptq.py
  fms_mo/run_quant.py
  fms_mo/utils/import_utils.py
  pyproject.toml
Labels: build
